[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = { default = "8000" }
PYTHONDONTWRITEBYTECODE = { default = "1" }
PYTHONUNBUFFERED = { default = "1" }
DEBUG = { default = "false" }

# These will be set as Railway environment variables
# OPENAI_API_KEY = "your-openai-api-key"
# TAVILY_API_KEY = "your-tavily-api-key"
# REDIS_URL = "redis://redis:6379" (will be auto-configured by Railway Redis service) 